name: Create bump version PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to change to (X.X.X)
        required: true
        type: string

jobs:
  bump-version-pr:
    name: Bump version PR
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Bump version
        run: |
          npm version --commit-hooks false --git-tag-version false ${{ inputs.version }}
          ./scripts/bump-version-changelog.js CHANGELOG.md ${{ inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: Bump version to ${{ inputs.version }}'
          branch: bump-version-to-${{ inputs.version }}
          title: 'chore: Bump version to ${{ inputs.version }}'

